# Site settings
title: Danl
email: daniel.l.budden@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of thoughts on programming, software development, open source
  software, and music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://d3spis3d.github.io" # the base hostname & protocol for your site
twitter_username: danlbudden
github_username:  d3spis3d
name: Daniel Budden

# Build settings
markdown: kramdown
